# Generated by Django 4.0.3 on 2022-03-28 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300, verbose_name='Item to buy/sell')),
                ('quantity', models.IntegerField(help_text='Item Quantity')),
                ('price_offer', models.FloatField(help_text='Item Price')),
                ('action', models.CharField(choices=[('b', 'buy'), ('s', 'sell')], max_length=1)),
                ('date_created', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
