# Generated by Django 4.0.3 on 2022-03-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instauni', '0002_alter_task_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_created']},
        ),
    ]
